apiVersion: v1
kind: Namespace
metadata:
  name: books
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: books
data:
  root-password: bWFyaWFkYg==
  user-password: YWJjMTIz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: books
data:
  config: |
    [mysqld]
    bind-address=0.0.0.0
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M
