apiVersion: mariadb.mmontes.io/v1alpha1
kind: Database
metadata:
  namespace: books
  name: books
spec:
  mariaDbRef:
    name: mariadb
  characterSet: utf8
  collate: utf8_general_ci
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: User
metadata:
  name: spring
  namespace: books
spec:
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: mariadb-secret
    key: user-password
  maxUserConnections: 20
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: Grant
metadata:
  name: grant-spring
  namespace: books
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
  database: books
  table: "*"
  username: spring
  grantOption: true
